[package]
name = "simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
robot = { path = "../robot", features = ["simulation"] }
station = { path = "../station" }
shared = { path = "../shared" }
kiss3d = "0.37"
nalgebra = "0.34.1"
tokio = { version = "1.49.0", features = ["full"] }
