[package]
name = "robot"
version = "0.1.0"
edition = "2024"

[features]
default = ["hardware"]
hardware = []
simulation = []

[dependencies]
shared = { path = "../shared" }
nalgebra = "0.34.1"
crossbeam = "0.8.4"
