[[subsystem.propulsion.thrusters]]
name = "1"
placement.position = [0.5, 0.5, 0.5]
placement.direction = [0.5, 0.5, 0.5]

[[subsystem.propulsion.thrusters]]
name = "2"
placement.position = [0.5, 0.5, 0.5]
placement.direction = [0.5, 0.5, 0.5]

[[subsystem.propulsion.thrusters]]
name = "3"
placement.position = [0.5, 0.5, 0.5]
placement.direction = [0.5, 0.5, 0.5]

[[subsystem.propulsion.thrusters]]
name = "4"
placement.position = [0.5, 0.5, 0.5]
placement.direction = [0.5, 0.5, 0.5]

[[subsystem.propulsion.thrusters]]
name = "5"
placement.position = [0.5, 0.5, 0.5]
placement.direction = [0.5, 0.5, 0.5]

[[subsystem.propulsion.thrusters]]
name = "6"
placement.position = [0.5, 0.5, 0.5]
placement.direction = [0.5, 0.5, 0.5]

[[subsystem.propulsion.thrusters]]
name = "7"
placement.position = [0.5, 0.5, 0.5]
placement.direction = [0.5, 0.5, 0.5]

[[subsystem.propulsion.thrusters]]
name = "8"
placement.position = [0.5, 0.5, 0.5]
placement.direction = [0.5, 0.5, 0.5]

[regulator.propulsion.velocity.linear]
surge  = { kp = 1.0, ki = 0.0, kd = 0.1 }
sway   = { kp = 1.0, ki = 0.0, kd = 0.1 }
heave  = { kp = 2.0, ki = 0.0, kd = 0.2 }

[regulator.propulsion.velocity.angular]
roll  = { kp = 0.5, ki = 0.0, kd = 0.05 }
pitch = { kp = 0.5, ki = 0.0, kd = 0.05 }
yaw   = { kp = 0.8, ki = 0.0, kd = 0.1 }